### PR TITLE
Revert "test"

### PR DESCRIPTION
**Pull request by k-nasa**
Reverts nasa-playground/ai-chan-playground#2

### CODE REVIEW

**Comment by ai-chann** [comment]
Assign reviewers randomly

**Comment by k-nasa** [comment]
@ai-chann r+

**Comment by ai-chann** [comment]
Delete branch automatically

**Comment by k-nasa** [comment]
@ai-chann r+

**Comment by ai-chann** [comment]
Delete branch automatically

**Comment by k-nasa** [comment]
@ai-chann r+

**Comment by k-nasa** [comment]
@ai-chann r+

**Comment by ai-chann** [comment]
Delete branch automatically

**Comment by k-nasa** [comment]
@ai-chann r+

**Comment by ai-chann** [comment]
Delete branch automatically

**Comment by k-nasa** [comment]
last2
@ai-chann r+

**Comment by ai-chann** [comment]
Delete branch automatically

**Comment by k-nasa** [comment]
@ai-chann r+

**Comment by ai-chann** [comment]
Delete branch automatically

**Comment by k-nasa** [comment]
last 
@ai-chann r+

**Comment by ai-chann** [comment]
Delete branch automatically

**Comment by k-nasa** [comment]
おー。よきよき

**Comment by k-nasa** [comment]
merge master

**Comment by k-nasa** [comment]
marge+ master

**Comment by k-nasa** [comment]
merge+ master

**Comment by ai-chann** [comment]
Try auto merge revert-2-test into master

**Comment by k-nasa** [comment]
うーん。多分良さそう

**Pull request merged**
